ROOT_DIR:=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

BUILDDIR?=$(ROOT_DIR)/build
TESTDIR=$(ROOT_DIR)/test
SRCDIR=$(ROOT_DIR)/src
SRCFILES=$(SRCDIR)/mem-reg.c

CFLAGS=-Wall -g -I$(SRCDIR)

VALGRIND?=valgrind
